pbench-fio: Continue, don't re-try iterations -When --continue-on-error=y is used pbench-fio will  not attempt to re-do iterations and will ignore  errors from postprocessing.  This may be useful if  one is running a test which they know will fail,  but still want all of the iterations to be tested.  An example of this is when the fio job file does  not have the iops log file.

diff --git a/agent/bench-scripts/pbench-fio b/agent/bench-scripts/pbench-fio
--- a/agent/bench-scripts/pbench-fio
+++ b/agent/bench-scripts/pbench-fio
@@ -68,6 +68,7 @@ tool_group="default"
 max_key_length=20
 primary_metric="readwrite_IOPS"
 histogram_interval_sec=$(getconf.py histogram-interval-sec pbench-fio)
+continue_on_error="n"
 if [ -z "$histogram_interval_sec" ] ;then
 	histogram_interval_sec=10
 fi
@@ -158,10 +159,13 @@ function usage {
 	printf "\n"
 	printf -- "\t--sysinfo=str            str= comma separated values of sysinfo to be collected\n"
 	printf "\t\tavailable: $(pbench-collect-sysinfo --options)\n"
+	printf "\n"
+	printf -- "\t--continue-on-error=[y|n]\n"
+	printf "\t\tif either fio postprocessing or iteration-sample postprocessing fails, continue running\n"
 }
 
 function fio_process_options() {
-	opts=$(getopt -q -o b:c:d:hj:r:s:t: --longoptions "help,max-stddev:,max-failures:,samples:,direct:,sync:,install,remote-only,clients:,client-file:,iodepth:,ioengine:,config:,jobs-per-dev:,job-mode:,rate-iops:,ramptime:,runtime:,test-types:,block-sizes:,file-size:,targets:,tool-group:,postprocess-only:,run-dir:,numjobs:,job-file:,sysinfo:,pre-iteration-script:,histogram-interval-sec:,histogram-interval-msec:" -n "getopt.sh" -- "$@");
+	opts=$(getopt -q -o b:c:d:hj:r:s:t: --longoptions "help,max-stddev:,max-failures:,samples:,direct:,sync:,install,remote-only,clients:,client-file:,iodepth:,ioengine:,config:,jobs-per-dev:,job-mode:,rate-iops:,ramptime:,runtime:,test-types:,block-sizes:,file-size:,targets:,tool-group:,postprocess-only:,run-dir:,numjobs:,job-file:,sysinfo:,pre-iteration-script:,histogram-interval-sec:,histogram-interval-msec:,continue-on-error:" -n "getopt.sh" -- "$@");
 	if [ $? -ne 0 ]; then
 		printf -- "${script_name} $*\n"
 		printf -- "\n"
@@ -393,6 +397,13 @@ function fio_process_options() {
 				sysinfo="$1"
 				shift;
 	        	fi
+			;;
+			--continue-on-error)
+			shift;
+			if [ -n "$1" ]; then
+				continue_on_error="$1"
+				shift;
+			fi
 			;;
 			--)
 			shift;
@@ -653,10 +664,13 @@ function fio_run_benchmark() {
 				iteration_dir=$benchmark_run_dir/$iteration
 				result_stddevpct=$maxstddevpct # this test case will get a "do-over" if the stddev is not low enough
 				failures=0
-				while [[ $(echo "if (${result_stddevpct} >= ${maxstddevpct}) 1 else 0" | bc) -eq 1 ]]; do
+				#while [[ $(echo "if (${result_stddevpct} >= ${maxstddevpct}) 1 else 0" | bc) -eq 1 ]]; do
+				while [ true ]; do
+					skip_process_samples=0
 					if [[ $failures -gt 0 ]]; then
-						echo "Restarting iteration $iteration ($count of $total_iterations)"
-						log "Restarting iteration $iteration ($count of $total_iterations)"
+						let attempts=$failures+1
+						echo "Restarting iteration (attempt #$attempts) $iteration ($count of $total_iterations)"
+						log "Restarting iteration (attempt #$attempts) $iteration ($count of $total_iterations)"
 					fi
 					if [ "$postprocess_only" = "n" ]; then
 						mkdir -p $iteration_dir
@@ -724,19 +738,28 @@ function fio_run_benchmark() {
 								sample_failed=1
 							fi
 							if [ $sample_failed -eq 1 ]; then
-								# we need all samples to be good, so bust out of testing samples now
-								break
+								if [ $continue_on_error == "n" ]; then
+									# we need all samples to be good, so bust out of testing samples now
+									break
+								else
+									skip_process_samples=1
+									log "sample #$sample failed, but continuing because continue_on_error = 'y'"
+								fi
 							fi
 						done
 					fi
-					echo "$script_path/postprocess/process-iteration-samples \"$iteration_dir\" \"$primary_metric\" \"$maxstddevpct\" \"$failures\" \"$max_failures\" \"$tar_nonref_data\" \"$keep_failed_tool_data\"" >"$iteration_dir/process-iteration-samples.cmd"
-					chmod +x "$iteration_dir/process-iteration-samples.cmd"
-					$iteration_dir/process-iteration-samples.cmd
-					fail=$?
-					if [ $fail -ne  0 ]; then
-						((failures++))
-					fi
-					if [ $fail -eq 0 -o $failures -ge $max_failures ]; then
+					if [ $skip_process_samples -eq 0 ]; then
+						echo "$script_path/postprocess/process-iteration-samples \"$iteration_dir\" \"$primary_metric\" \"$maxstddevpct\" \"$failures\" \"$max_failures\" \"$tar_nonref_data\" \"$keep_failed_tool_data\"" >"$iteration_dir/process-iteration-samples.cmd"
+						chmod +x "$iteration_dir/process-iteration-samples.cmd"
+						$iteration_dir/process-iteration-samples.cmd
+						fail=$?
+						if [ $fail -ne  0 ]; then
+							((failures++))
+						fi
+						if [ $continue_on_error == "n" -a $fail -eq 0 -o $failures -ge $max_failures ]; then
+							break
+						fi
+					else
 						break
 					fi
 				done
